apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-frontend
  labels:
   tier: frontend

spec:
  selector:
    matchLabels:
      app: myapp

  replicas: 3

  template:
    metadata:
      name: httpd-frontend
      labels:
        app: myapp
    spec:
      containers:
        - name: httpd-frontend
          image: httpd:2.4-alpine
 